### ISSUE TITLE
Google Play Camera Crash

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/open311-android#47]
```java
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65637, result=-1, data=null} to activity {org.open311.android/org.open311.android.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
	at org.open311.android.fragments.ReportFragment.onActivityResult(ReportFragment.java:971)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
	at org.open311.android.MainActivity.onActivityResult(MainActivity.java:232)
	at android.app.Activity.dispatchActivityResult(Activity.java:6193)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
	... 10 more
```

**Comment by milovanderlinden** [comment]
Related to not all Camera's returning data. Fix in progress.
