### ISSUE TITLE
App crashes on Android 6 when pressing Camera button

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/open311-android#8]
I installed the APK over USB debug on my OnePlus One running Android 6.0.1. When I press "Take a Picture" it immediatly crashes with the following exception in the log:

``` java
05-31 22:03:17.570 21601-21601/org.open311.android E/AndroidRuntime: FATAL EXCEPTION: main
  Process: org.open311.android, PID: 21601
  java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE cmp=com.android.camera2/com.android.camera.CaptureActivity } from ProcessRecord{85a3b41 21601:org.open311.android/u0a126} (pid=21601, uid=10126) with revoked permission android.permission.CAMERA
     at android.os.Parcel.readException(Parcel.java:1620)
     at android.os.Parcel.readException(Parcel.java:1573)
     at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2667)
     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1509)
     at android.app.Activity.startActivityForResult(Activity.java:3930)
     at android.app.Activity.startActivityForResult(Activity.java:3890)
     at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:855)
     at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:907)
     at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:927)
     at org.open311.android.fragments.ReportFragment.onPhotoButtonClicked(ReportFragment.java:552)
     at org.open311.android.fragments.ReportFragment.access$100(ReportFragment.java:68)
     at org.open311.android.fragments.ReportFragment$1.onClick(ReportFragment.java:223)
     at android.view.View.performClick(View.java:5204)
     at android.view.View$PerformClick.run(View.java:21156)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5466)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-31 22:03:24.815 21601-21601/org.open311.android I/Process: Sending signal. PID: 21601 SIG: 9
```

**Comment by milovanderlinden** [comment]
Implement something like this:
http://stackoverflow.com/questions/33078003/android-6-0-permission-error

**Comment by milovanderlinden** [comment]
Fixed it with backward compatibility. Tested on Android 5 and 6.
